/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import JavaSql.JavaMySql;
import Ux.DtableD;
import static Ventanas.Principal_Sistema.content;

import Ventanas.nuevoPrestamo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class Devolucion extends javax.swing.JPanel {

    JavaMySql con;
    Connection re;
    DtableD d = new DtableD();

    /**
     * Creates new form Principal
     */
    public Devolucion() {
        initComponents();
        con = new JavaMySql();
        re = con.conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        codPr = new javax.swing.JTextField();
        cedU = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaD = new javax.swing.JTable();
        button1 = new javax.swing.JPanel();
        btn_devolver = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        codLI = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        button2 = new javax.swing.JPanel();
        btnCancelDevolucion = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cajaU = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        cajaL = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("DEVOLUCIÓN DE LIBRO");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("ID de Préstamo");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Datos de Libro Prestado");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 200, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 0, 340));

        codPr.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 13)); // NOI18N
        codPr.setForeground(new java.awt.Color(102, 102, 102));
        codPr.setText("Ingrese el ID de Préstamo");
        codPr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        codPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codPrMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codPrMousePressed(evt);
            }
        });
        codPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPrActionPerformed(evt);
            }
        });
        add(codPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 30));

        cedU.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 13)); // NOI18N
        cedU.setForeground(new java.awt.Color(102, 102, 102));
        cedU.setText("Ingrese la Cédula de I");
        cedU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cedU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedUMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedUMousePressed(evt);
            }
        });
        cedU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedUActionPerformed(evt);
            }
        });
        cedU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedUKeyTyped(evt);
            }
        });
        add(cedU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 30));

        button.setBackground(new java.awt.Color(51, 73, 84));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buscar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 15)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buscar.setText("BUSCAR PRÉSTAMO");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_buscarMousePressed(evt);
            }
        });
        button.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 165, 50));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 165, 50));

        listaD.setBackground(new java.awt.Color(51, 73, 84));
        listaD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listaD.setForeground(new java.awt.Color(255, 255, 255));
        listaD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE PRÉSTAMO", "ID DE LIBRO", "CÉDULA DE IDENTIDAD", "CARRERA", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listaD.setRowHeight(20);
        jScrollPane1.setViewportView(listaD);
        if (listaD.getColumnModel().getColumnCount() > 0) {
            listaD.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 520, 70));

        button1.setBackground(new java.awt.Color(51, 73, 84));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_devolver.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 15)); // NOI18N
        btn_devolver.setForeground(new java.awt.Color(255, 255, 255));
        btn_devolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_devolver.setText("DEVOLVER LIBRO");
        btn_devolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_devolverMousePressed(evt);
            }
        });
        button1.add(btn_devolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 240, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("ID de Libro");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        codLI.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 13)); // NOI18N
        codLI.setForeground(new java.awt.Color(102, 102, 102));
        codLI.setText("Ingrese el ID de Libro");
        codLI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        codLI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codLIMousePressed(evt);
            }
        });
        codLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codLIActionPerformed(evt);
            }
        });
        add(codLI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 10));

        button2.setBackground(new java.awt.Color(51, 73, 84));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button2MousePressed(evt);
            }
        });
        button2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelDevolucion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 15)); // NOI18N
        btnCancelDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelDevolucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelDevolucion.setText("CANCELAR DEVOLUCIÓN");
        btnCancelDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelDevolucionMousePressed(evt);
            }
        });
        button2.add(btnCancelDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 240, 50));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Cédula de Identidad");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Datos del Estudiante");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 20));

        cajaU.setColumns(20);
        cajaU.setRows(5);
        cajaU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane2.setViewportView(cajaU);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 520, 80));

        cajaL.setColumns(20);
        cajaL.setRows(5);
        cajaL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane3.setViewportView(cajaL);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 520, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void codPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPrActionPerformed

    private void cedUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedUMousePressed
        if (cedU.getText().equals("Ingrese la Cedula de I")) {
            cedU.setText("");
        }
    }//GEN-LAST:event_cedUMousePressed

    private void codPrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codPrMousePressed
        if (codPr.getText().equals("Ingrese el ID de Prestamo")) {
            codPr.setText("");
        }
    }//GEN-LAST:event_codPrMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered

    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited

    }//GEN-LAST:event_buttonMouseExited
    // DEVOLVER
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed

    }//GEN-LAST:event_buttonMousePressed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MousePressed

    private void codLIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codLIMousePressed
        if (codLI.getText().equals("Ingrese el ID de Libro")) {
            codLI.setText("");
        }


    }//GEN-LAST:event_codLIMousePressed

    private void codLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codLIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codLIActionPerformed

    private void button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button2MouseEntered

    private void button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button2MouseExited

    private void button2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2MousePressed

    private void btn_buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMousePressed

        if ((cedU.getText().equals("Ingrese la Cedula de I") || cedU.getText().equals(""))) {

        } else {
            String c = cedU.getText();
            String l = codLI.getText();
            String p = codPr.getText();
            generarBusqueda(c, l, p);
        }
    }//GEN-LAST:event_btn_buscarMousePressed

    private void btn_devolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devolverMousePressed
        int idcell = listaD.getSelectedRow();

        if (idcell <= -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR EL REGISTRO A MODIFICAR \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            String valor = listaD.getValueAt(idcell, 0).toString();

            try {
                Statement stm = re.createStatement();
                stm.executeUpdate("UPDATE `prestamo` SET `estado`='No Deudor' WHERE `idPrestamo`= '" + valor + "'");
                javax.swing.JOptionPane.showMessageDialog(this, "LIBRO DEVUELTO Y PRESTAMO MODIFICADO \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(Devolucion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_devolverMousePressed

    private void btnCancelDevolucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelDevolucionMousePressed
        //AR SE TRABAJO EL BOTON DE CANCELAR DEVOLUCION   
        // Abrir sección
        Principal p1 = new Principal();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCancelDevolucionMousePressed

    private void cedUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedUMouseClicked
        cedU.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cedUMouseClicked

    private void codPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codPrMouseClicked
        codPr.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_codPrMouseClicked

    private void cedUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedUKeyTyped
//        if (cedU.getText().equalsIgnoreCase("Ingrese la Cédula de I")
//                || cedU.getText().equalsIgnoreCase("")) {
//            //NO HAGO NADA
//        } else {
//            String c = cedU.getText();
//            String l = codLI.getText();
//            String p = codPr.getText();
//            busquedaEscrita(c, l, p);
//        }
    }//GEN-LAST:event_cedUKeyTyped

    private void cedUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedUActionPerformed

    private void generarBusqueda(String c, String l, String p) {
        int n = 0, i = 0;
        String a = "", b = "";
        if (!c.equals("Ingrese la Cedula de I") && !c.equals("") && !l.equals("Ingrese el ID de Libro") && !l.equals("") && !p.equals("Ingrese el ID de Prestamo") && !p.equals("")) {
            try {
                Statement stm = re.createStatement();
                ResultSet r = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                while (r.next()) {
                    if (r.getString("CodUsuario").equals(c) && r.getString("CodLibro").equals(l) && r.getString("idPrestamo").equals(p)) {
                        n++;
                    }
                }
                String list[][] = new String[n][5];
                ResultSet rs = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                while (rs.next()) {
                    if (rs.getString("CodUsuario").equals(c) && rs.getString("CodLibro").equals(l) && rs.getString("idPrestamo").equals(p)) {
                        n--;
                        list[n][0] = rs.getString("idPrestamo");
                        list[n][1] = rs.getString("CodLibro");
                        b = rs.getString("CodLibro");
                        list[n][2] = rs.getString("CodUsuario");
                        a = rs.getString("CodUsuario");
                        list[n][3] = carreraU(rs.getString("CodUsuario"));
                        list[n][4] = rs.getString("estado");
                    }

                }
                listaD.setModel(new javax.swing.table.DefaultTableModel(
                        list,
                        new String[]{
                            "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                        }));
                listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

                DatosUL(a, b);
            } catch (Exception e) {

            }

        } else {
            if (!c.equals("Ingrese la Cedula de I") && !c.equals("") && !l.equals("Ingrese el ID de Libro") && !l.equals("")) {
                try {
                    Statement stm = re.createStatement();
                    ResultSet r = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                    while (r.next()) {
                        if (r.getString("CodUsuario").equals(c) && r.getString("CodLibro").equals(l)) {
                            n++;
                        }
                    }
                    String list[][] = new String[n][5];
                    ResultSet rs = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                    while (rs.next()) {
                        if (rs.getString("CodUsuario").equals(c) && rs.getString("CodLibro").equals(l)) {
                            n--;
                            list[n][0] = rs.getString("idPrestamo");
                            list[n][1] = rs.getString("CodLibro");
                            b = rs.getString("CodLibro");;
                            list[n][2] = rs.getString("CodUsuario");
                            a = rs.getString("CodUsuario");
                            list[n][3] = carreraU(rs.getString("CodUsuario"));
                            list[n][4] = rs.getString("estado");
                        }

                    }
                    listaD.setModel(new javax.swing.table.DefaultTableModel(
                            list,
                            new String[]{
                                "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                            }));
                    listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

                    DatosUL(a, b);
                } catch (Exception e) {

                }
            } else {
                if (!c.equals("Ingrese la Cedula de I") && !c.equals("") && !p.equals("Ingrese el ID de Prestamo") && !p.equals("")) {
                    try {
                        Statement stm = re.createStatement();
                        ResultSet r = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                        while (r.next()) {
                            if (r.getString("CodUsuario").equals(c) && r.getString("idPrestamo").equals(p)) {
                                n++;
                            }
                        }
                        String list[][] = new String[n][5];
                        ResultSet rs = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                        while (rs.next()) {
                            if (rs.getString("CodUsuario").equals(c) && rs.getString("idPrestamo").equals(p)) {
                                n--;
                                list[n][0] = rs.getString("idPrestamo");
                                list[n][1] = rs.getString("CodLibro");
                                b = rs.getString("CodLibro");
                                list[n][2] = rs.getString("CodUsuario");
                                a = rs.getString("CodUsuario");
                                list[n][3] = carreraU(rs.getString("CodUsuario"));
                                list[n][4] = rs.getString("estado");
                            }

                        }
                        listaD.setModel(new javax.swing.table.DefaultTableModel(
                                list,
                                new String[]{
                                    "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                                }));
                        listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

                        DatosUL(a, b);
                    } catch (Exception e) {

                    }
                } else {
                    if (!c.equals("Ingrese la Cedula de I") && !c.equals("")) {
                        //JOptionPane.showMessageDialog(null, "carnet "+c);
                        try {
                            Statement stm = re.createStatement();
                            ResultSet r = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                            while (r.next()) {
                                if (r.getString("CodUsuario").equals(c)) {
                                    n++;
                                }
                            }

                            String list[][] = new String[n][5];
                            ResultSet res = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                            while (res.next()) {
                                if (res.getString("CodUsuario").equals(c)) {
                                    n--;
                                    list[n][0] = res.getString("idPrestamo");
                                    list[n][1] = res.getString("CodLibro");
                                    b = res.getString("CodLibro");
                                    list[n][2] = res.getString("CodUsuario");
                                    a = res.getString("CodUsuario");
                                    list[n][3] = carreraU(res.getString("CodUsuario"));
                                    list[n][4] = res.getString("estado");
                                }

                            }
                            listaD.setModel(new javax.swing.table.DefaultTableModel(
                                    list,
                                    new String[]{
                                        "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                                    }));
                            listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

                            DatosUL(a, b);
                        } catch (SQLException ex) {
                            Logger.getLogger(Devolucion.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        if (!l.equals("Ingrese el ID de Libro") && !l.equals("")) {
                            try {
                                Statement stm = re.createStatement();
                                ResultSet r = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                                while (r.next()) {
                                    if (r.getString("CodLibro").equals(l)) {
                                        n++;
                                    }
                                }
                                String list[][] = new String[n][5];
                                ResultSet rs = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                                while (rs.next()) {
                                    if (rs.getString("CodLibro").equals(l)) {
                                        n--;
                                        list[n][0] = rs.getString("idPrestamo");
                                        list[n][1] = rs.getString("CodLibro");
                                        b = rs.getString("CodLibro");
                                        list[n][2] = rs.getString("CodUsuario");
                                        a = rs.getString("CodUsuario");
                                        list[n][3] = carreraU(rs.getString("CodUsuario"));
                                        list[n][4] = rs.getString("estado");
                                    }

                                }
                                listaD.setModel(new javax.swing.table.DefaultTableModel(
                                        list,
                                        new String[]{
                                            "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                                        }));
                                listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

                                DatosUL(a, b);
                            } catch (Exception e) {

                            }
                        } else {
                            if (!p.equals("Ingrese el ID de Prestamo") && !p.equals("")) {
                                try {
                                    Statement stm = re.createStatement();
                                    ResultSet r = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                                    while (r.next()) {
                                        if (r.getString("idPrestamo").equals(p)) {
                                            n++;
                                        }
                                    }
                                    String list[][] = new String[n][5];
                                    ResultSet rs = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor' OR `estado` = 'moroso'");

                                    while (rs.next()) {
                                        if (rs.getString("idPrestamo").equals(p)) {
                                            n--;
                                            list[n][0] = rs.getString("idPrestamo");
                                            list[n][1] = rs.getString("CodLibro");
                                            b = rs.getString("CodLibro");
                                            list[n][2] = rs.getString("CodUsuario");
                                            a = rs.getString("CodUsuario");
                                            list[n][3] = carreraU(rs.getString("CodUsuario"));
                                            list[n][4] = rs.getString("estado");
                                        }

                                    }
                                    listaD.setModel(new javax.swing.table.DefaultTableModel(
                                            list,
                                            new String[]{
                                                "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                                            }));
                                    listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

                                    DatosUL(a, b);
                                } catch (Exception e) {

                                }
                            }
                        }
                    }

                }

            }
        }
    }

    private void DatosUL(String u, String l) throws SQLException {
        Statement stm = re.createStatement();
        ResultSet r = stm.executeQuery("SELECT * FROM `usuario` WHERE `matricula` = '" + u + "'");
        while (r.next()) {
            cajaU.setText("Nombre: " + r.getString("nombre") + "\n Apellido Paterno: " + r.getString("apP") + "\n Apellido Materno: "
                    + r.getString("apM") + "\n Cedula de Identidad: " + r.getString("matricula") + "\n Carrera: " + r.getString("carrera"));
        }

        ResultSet res = stm.executeQuery("SELECT * FROM `libro` WHERE `idlibro` = '" + l + "'");
        while (res.next()) {
            cajaL.setText("Titulo: " + res.getString("titulo") + "\n Categoria: " + res.getString("categoria") + "\n Carrera: " + res.getString("carrera") + "\n Autor: " + res.getString("autor"));
        }
    }

    private String carreraU(String idU) throws SQLException {
        String car = "";

        Statement stm = re.createStatement();

        ResultSet r = stm.executeQuery("SELECT `carrera` FROM `usuario` WHERE `matricula` = '" + idU + "'");
        while (r.next()) {
            car = r.getString("carrera");
        }

        return car;
    }

    private void busquedaEscrita(String c, String l, String p) {
        int n = 0;
        String a = "", b = "";
        try {
            Statement stm = re.createStatement();                   
            String list[][] = new String[n][5];
            ResultSet rs = stm.executeQuery("SELECT * FROM prestamo p inner join libro l on l.idlibro = p.CodLibro WHERE  p.CodUsuario like '%"+c+"%';");
            System.out.println(c);

            if(rs.next()) {
                list[n][0] = rs.getString("idPrestamo");
                list[n][1] = rs.getString("CodLibro");

                b = rs.getString("CodLibro");

                list[n][2] = rs.getString("CodUsuario");

                a = rs.getString("CodUsuario");

                list[n][3] = carreraU(rs.getString("carrera"));
                list[n][4] = rs.getString("estado");
                System.out.println("El valor si esta");

            } else {
                System.out.println("El valor no es");
            }

            listaD.setModel(new javax.swing.table.DefaultTableModel(
                    list,
                    new String[]{
                        "ID DE PRESTAMO", "ID DE LIBRO", "CEDULA DE IDENTIDAD", "CARRERA", "ESTADO"
                    }));

            listaD.setDefaultRenderer(listaD.getColumnClass(4), d);

            DatosUL(a, b);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnCancelDevolucion;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_devolver;
    private javax.swing.JPanel button;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button2;
    private javax.swing.JTextArea cajaL;
    private javax.swing.JTextArea cajaU;
    private javax.swing.JTextField cedU;
    private javax.swing.JTextField codLI;
    private javax.swing.JTextField codPr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable listaD;
    // End of variables declaration//GEN-END:variables
}
