/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import JavaSql.JavaMySql;
import Ventanas.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static Ventanas.Principal_Sistema.content;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class NuevoAdmin extends javax.swing.JPanel {

    JavaMySql con;
    Connection re;
    boolean edit;
    int idus;

    /**
     * Creates new form Principal
     */
    public NuevoAdmin() {
        initComponents();
        con = new JavaMySql();
        re = con.conexion();
        edit = false;
        Title.setText("NUEVO USUARIO");

    }

    public NuevoAdmin(int usid, String user, String password, String cargo, String nombre, String paterno, String materno) {
        initComponents();
        con = new JavaMySql();
        re = con.conexion();
        Title.setText("EDITAR USUARIO");
        edit = true;
        //ALMACENANDO PARAMETROS EN LAS CASILLAS DE TEXTO   
        idus = usid;
        nombreTxt.setText(nombre);
        claveTxt.setText(password);
        maternoTxt.setText(materno);
        paternoTxt.setText(paterno);
        cargoTxt.setText(cargo);
        userTxt.setText(user);
        btnRegistrar.setText("");
        btnRegistrar.setText("Editar");
        edit = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cargoTxt = new javax.swing.JTextField();
        userTxt = new javax.swing.JTextField();
        maternoTxt = new javax.swing.JTextField();
        paternoTxt = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        button1 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        claveTxt = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 260, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Usuario");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 20));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Clave");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Apellido Materno");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Cargo");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 260, 10));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Apellido Paterno");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 260, 10));

        cargoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cargoTxt.setForeground(new java.awt.Color(153, 153, 153));
        cargoTxt.setText("Ingrese su cargo");
        cargoTxt.setBorder(null);
        cargoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargoTxtMouseClicked(evt);
            }
        });
        add(cargoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 260, 30));

        userTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(153, 153, 153));
        userTxt.setText("Ingrese Usuario");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTxtMouseClicked(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 30));

        maternoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maternoTxt.setForeground(new java.awt.Color(153, 153, 153));
        maternoTxt.setText("Ingrese Materno");
        maternoTxt.setBorder(null);
        maternoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maternoTxtMouseClicked(evt);
            }
        });
        add(maternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 30));

        paternoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paternoTxt.setForeground(new java.awt.Color(153, 153, 153));
        paternoTxt.setText("Ingrese Paterno");
        paternoTxt.setBorder(null);
        paternoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paternoTxtMouseClicked(evt);
            }
        });
        paternoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paternoTxtActionPerformed(evt);
            }
        });
        add(paternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 260, 30));

        button.setBackground(new java.awt.Color(51, 73, 84));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        button.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 50));

        button1.setBackground(new java.awt.Color(51, 73, 84));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        button1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 140, 50));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Nombre");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        nombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(153, 153, 153));
        nombreTxt.setText("Ingrese su nombre");
        nombreTxt.setBorder(null);
        nombreTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTxtMouseClicked(evt);
            }
        });
        add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 260, 30));

        claveTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        claveTxt.setForeground(new java.awt.Color(153, 153, 153));
        claveTxt.setText("jPasswordField1");
        claveTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claveTxtMouseClicked(evt);
            }
        });
        add(claveTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered

    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited

    }//GEN-LAST:event_buttonMouseExited

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed

        /*if(     name.getText().equals("Ingrese el nombre")
            || ap1.getText().equals("Ingrese el apellido paterno")
            || ap2.getText().equals("Ingrese el apellido materno")
            || DevFecha(fech.getDatoFecha()).equals("Seleccinar fecha")
            || carr.getSelectedItem().toString().equals("ninguno")
            || tel.getText().equals("Ingrese un número telefónico")

            || cedu.getText().equals("Ingrese el Cod de Registro")
            || nroR.getText().equals("Nro")
        )
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            name.requestFocus();
        }
        else
        {

            String uname = name.getText();
            String uapp = ap1.getText();
            String uapm = ap2.getText();
            String uafe = DevFecha(fech.getDatoFecha());

            String utel = tel.getText();
            String ucarr=(String)carr.getSelectedItem();
            String umat=cedu.getText();
            String unro=nroR.getText();
            String opt=(String) seleccionG.getSelectedItem();

            if(uname == null
                || "".equals(uname)
                || uapp == null
                || "".equals(uapp)
                || uapm == null
                || "".equals(uapm)
                || uafe == null
                || "".equals(uafe)

                || utel == null
                || "".equals(utel))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                name.requestFocus();
            }
            else{
                try {
                    if(edit)
                    {
                        JOptionPane.showMessageDialog(this,"llego aqui 2");
                        EditUser(idus,uname, uapp, uapm, uafe, umat,opt,unro,ucarr, utel);
                    }
                    else
                    InsertUser(idus,uname, uapp, uapm, uafe, umat,opt,unro,ucarr, utel);

                    name.setText("");
                    ap1.setText("");
                    ap2.setText("");

                    carr.setSelectedItem("");
                    tel.setText("");

                    if(edit){
                        Usuario p1 = new Usuario();
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);

                        content.removeAll();
                        content.add(p1, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }*/
    }//GEN-LAST:event_buttonMousePressed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MousePressed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseClicked
        userTxt.setText("");
        userTxt.setForeground(Color.black);
    }//GEN-LAST:event_userTxtMouseClicked

    private void maternoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maternoTxtMouseClicked
        maternoTxt.setText("");
        maternoTxt.setForeground(Color.black);
    }//GEN-LAST:event_maternoTxtMouseClicked

    private void paternoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paternoTxtMouseClicked
        paternoTxt.setText("");
        paternoTxt.setForeground(Color.black);
    }//GEN-LAST:event_paternoTxtMouseClicked

    private void cargoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoTxtMouseClicked
        cargoTxt.setText("");
        cargoTxt.setForeground(Color.black);
    }//GEN-LAST:event_cargoTxtMouseClicked

    private void nombreTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTxtMouseClicked
        nombreTxt.setText("");
        nombreTxt.setForeground(Color.black);
    }//GEN-LAST:event_nombreTxtMouseClicked

    private void paternoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paternoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paternoTxtActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        //METODO PARA REGISTRAR UN ADMIN
        validarCamposTexto();
        try {
            if (edit) {
                editarUsuario();
            } else {
                enviarRegistro();
            }

        } catch (SQLException ex) {
            Logger.getLogger(NuevoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        Admin p1 = new Admin();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void claveTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveTxtMouseClicked
       claveTxt.setText("");
       claveTxt.setForeground(Color.black);
    }//GEN-LAST:event_claveTxtMouseClicked

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    public void InsertUser(int idus,
            String name,
            String app,
            String apm,
            String fech,
            String matri,
            String mod,
            String nro,
            String carre,
            String tel)
            throws SQLException {
        Statement stm = re.createStatement();

        JOptionPane.showMessageDialog(null, fech);
        //convierte edad
        DateTimeFormatter date = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaNacimiento = LocalDate.parse(fech, date);
        LocalDate fechaActual = LocalDate.now();

        Period periodo = Period.between(fechaNacimiento, fechaActual);

        int edad = periodo.getYears();
        //----------------------------

        ResultSet counter = stm.executeQuery("SELECT * FROM `usuario`");

        int count = 0;
        while (counter.next()) {
            count++;
        }

        int i = 0, idn = 0;
        ResultSet re = stm.executeQuery("SELECT * FROM `usuario`");
        while (re.next()) {
            idn = re.getInt("idUsuario");
        }
        idn++;

        stm.executeUpdate("INSERT INTO `usuario` (`idUsuario`,`nombre`, `apP`, `apM`, `feN`,`matricula`,`sem_ano`,`nro_est`,`carrera`,`tel`) VALUES ('" + idn + "','" + name + "', '" + app + "', '" + apm + "', '" + fech + "', '" + matri + "','" + mod + "','" + nro + "','" + carre + "','" + tel + "')");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        Usuario p1 = new Usuario();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    public void EditUser(int id,
            String name,
            String app,
            String apm,
            String fech,
            String matri,
            String mod,
            String nro,
            String carre,
            String tel)
            throws SQLException {
        Statement stm = re.createStatement();

        DateTimeFormatter date = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaNacimiento = LocalDate.parse(fech, date);
        LocalDate fechaActual = LocalDate.now();

        Period periodo = Period.between(fechaNacimiento, fechaActual);

        int edad = periodo.getYears();

        stm.executeUpdate("UPDATE `usuario` SET `nombre` = '" + name + "', `apP` = '" + app + "', `apM` = '" + apm + "',`feN`= '" + fech + "',`matricula`= '" + matri + "',`sem_ano`= '" + mod + "',`nro_est`= '" + nro + "',`carrera`= '" + carre + "',`tel`= '" + tel + "' WHERE `idUsuario` = " + id + ";");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        Usuario p1 = new Usuario();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    //METODO QUE VALIDA CAMPOS DE TEXTO VACIOS
    public void validarCamposTexto() {
        if (nombreTxt.getText().equals("Ingrese su nombre")
                || paternoTxt.getText().equals("Ingrese Paterno")
                || maternoTxt.getText().equals("Ingrese Materno")
                || cargoTxt.getText().equals("Ingrese su cargo")
                || userTxt.getText().equals("Ingrese usuario")
                || claveTxt.getText().equals("Ingrese Clave")
                || nombreTxt.getText().equals("")
                || paternoTxt.getText().equals("")
                || maternoTxt.getText().equals("")
                || cargoTxt.getText().equals("")
                || userTxt.getText().equals("")
                || claveTxt.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
    }

    public void enviarRegistro() throws SQLException {
        Statement stm = re.createStatement();
        //----------------------------
        stm.executeUpdate("INSERT INTO `biblioteca`.`admi` (`UAdmi`, `clave`, `cargo`, `nombre`, `paterno`, `materno`, `estado`) "
                + "VALUES ( '" + userTxt.getText() + "', '" + String.valueOf(claveTxt.getPassword()) + "', '" + cargoTxt.getText() + "',"
                + " '" + nombreTxt.getText() + "', '" + paternoTxt.getText() + "', '" + maternoTxt.getText() + "', '1');");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        Admin p1 = new Admin();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    public void editarUsuario() throws SQLException {

        Statement stm = re.createStatement();
        //----------------------------
        stm.executeUpdate("UPDATE admi SET UAdmi = '" + userTxt.getText() + "', clave = '" + String.valueOf(claveTxt.getPassword()) + "',"
                + "cargo = '" + cargoTxt.getText() + "',nombre = '" + nombreTxt.getText() + "',"
                + " paterno = '" + paternoTxt.getText() + "',materno = '" + maternoTxt.getText() + "'"
                + " WHERE (idadmi = '" + idus + "');");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario Editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        //LLAMANDO A LA SECCION ADMIN
        Admin p1 = new Admin();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JPanel button;
    private javax.swing.JPanel button1;
    private javax.swing.JTextField cargoTxt;
    private javax.swing.JPasswordField claveTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField maternoTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField paternoTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
