/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import JavaSql.JavaMySql;
import Ventanas.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static Ventanas.Principal_Sistema.content;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class NuevoUsuario extends javax.swing.JPanel {

    JavaMySql con;
    Connection re;
    boolean edit;
    int idus;
    /**
     * Creates new form Principal
     */
    public NuevoUsuario() {
        initComponents();
        con = new JavaMySql();
        re = con.conexion();
        edit = false;
        
        Title.setText("NUEVO ESTUDIANTE");
        btn_U_1.setText("REGISTRAR ESTUDIANTE");
        btn_U_2.setText("CANCELAR REGISTRO");
    }
    
    public NuevoUsuario(int usid,String usname, String usap1, String usap2, String fe,String ma,String s,String nr,String ca,String ustel) 
    {
        initComponents();
        con = new JavaMySql();
        re = con.conexion();
        
        Title.setText("EDITAR ESTUDIANTE");
        btn_U_1.setText("GUARDAR CAMBIOS");
        btn_U_2.setText("CANCELAR EDICIÓN");
        
        
        Date e;
        try {
            e = DevFechaD(fe);
            fech.setDatoFecha(e);
        } catch (ParseException ex) {
            Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        idus=usid;
        name.setText(usname);
        ap1.setText(usap1);
        ap2.setText(usap2);
        
        cedu.setText(ma);
        seleccionG.setSelectedItem(s);
        nroR.setText(nr);
        carr.setSelectedItem(ca);
        
        tel.setText(ustel);
        edit = true;
        
        
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        tel = new javax.swing.JTextField();
        button = new javax.swing.JPanel();
        btn_U_1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        ap1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        ap2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        nroR = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        seleccionG = new javax.swing.JComboBox<>();
        Text9 = new javax.swing.JLabel();
        cedu = new javax.swing.JTextField();
        fech = new rojeru_san.rsdate.RSDateChooser();
        button1 = new javax.swing.JPanel();
        btn_U_2 = new javax.swing.JLabel();
        carr = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Teléfono");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Carrera ");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        tel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tel.setForeground(new java.awt.Color(102, 102, 102));
        tel.setText("Ingrese un número telefónico");
        tel.setBorder(null);
        tel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telMousePressed(evt);
            }
        });
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });
        add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 260, 30));

        button.setBackground(new java.awt.Color(51, 73, 84));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_U_1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        btn_U_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_U_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.add(btn_U_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 260, 50));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Nombre");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Ingrese el nombre");
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 20));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Apellido Paterno");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        ap1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ap1.setForeground(new java.awt.Color(102, 102, 102));
        ap1.setText("Ingrese el apellido paterno");
        ap1.setBorder(null);
        ap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ap1MousePressed(evt);
            }
        });
        ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1ActionPerformed(evt);
            }
        });
        add(ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 10));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Fecha de Nacimiento");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Apellido Materno");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        ap2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ap2.setForeground(new java.awt.Color(102, 102, 102));
        ap2.setText("Ingrese el apellido materno");
        ap2.setBorder(null);
        ap2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ap2MousePressed(evt);
            }
        });
        ap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2ActionPerformed(evt);
            }
        });
        add(ap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 10));

        nroR.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nroR.setForeground(new java.awt.Color(102, 102, 102));
        nroR.setText("Nro");
        nroR.setBorder(null);
        nroR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nroRMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nroRMousePressed(evt);
            }
        });
        nroR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroRActionPerformed(evt);
            }
        });
        add(nroR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 70, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("nro de Año/Semestre de carrera  ");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 260, 10));

        seleccionG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestral", "Anual" }));
        seleccionG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionGActionPerformed(evt);
            }
        });
        add(seleccionG, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 120, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Cédula de Identidad");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        cedu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cedu.setForeground(new java.awt.Color(102, 102, 102));
        cedu.setText("Ingrese la C.I.");
        cedu.setBorder(null);
        cedu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ceduMousePressed(evt);
            }
        });
        cedu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceduActionPerformed(evt);
            }
        });
        add(cedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 260, 30));

        fech.setBackground(new java.awt.Color(51, 73, 84));
        fech.setColorBackground(new java.awt.Color(51, 73, 84));
        fech.setColorButtonHover(new java.awt.Color(51, 73, 84));
        fech.setColorDiaActual(new java.awt.Color(51, 73, 84));
        fech.setColorForeground(new java.awt.Color(0, 0, 0));
        fech.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        fech.setFormatoFecha("dd/MM/yyyy");
        fech.setFuente(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        fech.setMaximumSize(new java.awt.Dimension(300, 200));
        fech.setPreferredSize(new java.awt.Dimension(100, 20));
        add(fech, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 260, 30));

        button1.setBackground(new java.awt.Color(51, 73, 84));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_U_2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        btn_U_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_U_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_U_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_U_2MousePressed(evt);
            }
        });
        button1.add(btn_U_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 260, 40));

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 50));

        carr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguno", "Ing de Sistemas y TIC", "Contaduria y Auditoria de Sistemas", "Ing Comercial y Empresarial", "Medicina Veterinaria", "Ing Civil", "Ing Zootecnica", "Ing Agronomica", "Arquitectura y Urbanismo", "Trabajo Social", "Ing de Hardware y Robotica", "Ing de Software y Multimedia", " " }));
        add(carr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 30));
    }// </editor-fold>//GEN-END:initComponents
private Date DevFechaD(String f) throws ParseException
{
    SimpleDateFormat formato=new SimpleDateFormat("dd/MM/yyyy");
    Date fecha=formato.parse(f);
    
    return fecha;
}
    private String DevFecha(Date f)
{
    
    /*otro*/
               
        char af,bf,c,d,e,g,h,i;
        SimpleDateFormat fc=new SimpleDateFormat("dd/MM/yyyy");
        String fec=fc.format(f);
        af=fec.charAt(0);
        String dia1=Character.toString(af);
        bf=fec.charAt(1);
        String dia2=Character.toString(bf);
        
        c=fec.charAt(3);
        String m1=Character.toString(c);
        d=fec.charAt(4);
        String m2=Character.toString(d);
        
        e=fec.charAt(6);
        String y1=Character.toString(e);
        g=fec.charAt(7);
        String y2=Character.toString(g);
        h=fec.charAt(8);
        String y3=Character.toString(h);
        i=fec.charAt(9);
        String y4=Character.toString(i);
        
        
        
        String nfecha = dia1+dia2+"/"+m1+m2+"/"+y1+y2+y3+y4;
        
        return nfecha;
       

}
    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void telMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telMousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
        name.setText("Ingrese el nombre");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido paterno");
       if(ap2.getText().equals("") || ap2.getText() == null || ap2.getText().equals(" "))
        ap2.setText("Ingrese el apellido materno");
       if(nroR.getText().equals("") || nroR.getText() == null || nroR.getText().equals(" "))
        nroR.setText("Nro");
       if(cedu.getText().equals("") || cedu.getText() == null || cedu.getText().equals(" "))
        cedu.setText("Ingrese la C.I.");
       
       if(tel.getText().equals("Ingrese un número telefónico"))
        tel.setText("");
    }//GEN-LAST:event_telMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        
    }//GEN-LAST:event_buttonMouseExited

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed
        if(name.getText().equals("Ingrese el nombre"))
        name.setText("");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido paterno");
       if(ap2.getText().equals("") || ap2.getText() == null || ap2.getText().equals(" "))
        ap2.setText("Ingrese el apellido materno");
       if(nroR.getText().equals("") || nroR.getText() == null || nroR.getText().equals(" "))
        nroR.setText("Nro");
       if(cedu.getText().equals("") || cedu.getText() == null || cedu.getText().equals(" "))
        cedu.setText("Ingrese la C.I.");
       if(tel.getText().equals("") || tel.getText() == null || tel.getText().equals(" "))
        tel.setText("Ingrese un número telefónico");
    }//GEN-LAST:event_nameMousePressed

    private void ap1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap1MousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
        name.setText("Ingrese el nombre");
       if(ap1.getText().equals("Ingrese el apellido paterno"))
        ap1.setText("");
       if(ap2.getText().equals("") || ap2.getText() == null || ap2.getText().equals(" "))
        ap2.setText("Ingrese el apellido materno");
        if(nroR.getText().equals("") || nroR.getText() == null || nroR.getText().equals(" "))
        nroR.setText("Nro");
       if(cedu.getText().equals("") || cedu.getText() == null || cedu.getText().equals(" "))
        cedu.setText("Ingrese la C.I.");
       
       if(tel.getText().equals("") || tel.getText() == null || tel.getText().equals(" "))
        tel.setText("Ingrese un número telefónico");
    }//GEN-LAST:event_ap1MousePressed

    private void ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap1ActionPerformed

      
    
    
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
    // REGISTRAR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(     name.getText().equals("Ingrese el nombre") 
                || ap1.getText().equals("Ingrese el apellido paterno")
                || ap2.getText().equals("Ingrese el apellido materno") 
                || DevFecha(fech.getDatoFecha()).equals("Seleccinar fecha")
                || carr.getSelectedItem().toString().equals("ninguno")
                || tel.getText().equals("Ingrese un número telefónico")
                
                || cedu.getText().equals("Ingrese el Cod de Registro")
                || nroR.getText().equals("Nro")
          )
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            name.requestFocus();
        }
        else
        {
            
            String uname = name.getText();
            String uapp = ap1.getText();
            String uapm = ap2.getText();
            String uafe = DevFecha(fech.getDatoFecha());
           
            String utel = tel.getText();
            String ucarr=(String)carr.getSelectedItem();
            String umat=cedu.getText();
            String unro=nroR.getText();
            String opt=(String) seleccionG.getSelectedItem();

            if(uname == null 
                    || "".equals(uname) 
                    || uapp == null 
                    || "".equals(uapp) 
                    || uapm == null 
                    || "".equals(uapm) 
                    || uafe == null 
                    || "".equals(uafe) 
                    
                    
                    || utel == null 
                    || "".equals(utel))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                name.requestFocus();
            }
            else{ 
                try {
                    if(edit)
                    {                  
                        EditUser(idus,uname, uapp, uapm, uafe, umat,opt,unro,ucarr, utel);
                    }
                    else
                        InsertUser(idus,uname, uapp, uapm, uafe, umat,opt,unro,ucarr, utel);

                    name.setText("");
                    ap1.setText("");
                    ap2.setText("");
                    
                    carr.setSelectedItem("");
                    tel.setText("");

                    if(edit){
                        Usuario p1 = new Usuario();
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);

                        content.removeAll();
                        content.add(p1, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_buttonMousePressed

    

    private void ap2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap2MousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
        name.setText("Ingrese el nombre");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido paterno");
       if(ap2.getText().equals("Ingrese el apellido materno"));
        ap2.setText("");
      
       if(nroR.getText().equals("") || nroR.getText() == null || nroR.getText().equals(" "))
        nroR.setText("Nro");
       if(cedu.getText().equals("") || cedu.getText() == null || cedu.getText().equals(" "))
        cedu.setText("Ingrese la C.I.");
       if(tel.getText().equals("") || tel.getText() == null || tel.getText().equals(" "))
        tel.setText("Ingrese un número telefónico");
    }//GEN-LAST:event_ap2MousePressed

    private void ap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap2ActionPerformed

    private void nroRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nroRMousePressed
       nroR.setText("");
    }//GEN-LAST:event_nroRMousePressed

    private void nroRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nroRActionPerformed

    private void ceduMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceduMousePressed
        if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
        name.setText("Ingrese el nombre");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido paterno");
       if(ap2.getText().equals("") || ap2.getText() == null || ap2.getText().equals(" "))
        ap2.setText("Ingrese el apellido materno");
       if(cedu.getText().equals("Ingrese la C.I.") || cedu.getText() == null || cedu.getText().equals(" "))
        cedu.setText("");
       if(nroR.getText().equals("") || nroR.getText() == null || nroR.getText().equals(" "))
        nroR.setText("Nro");
       if(tel.getText().equals("") || tel.getText() == null || tel.getText().equals(" "))
        tel.setText("Ingrese un número telefónico");        // TODO add your handling code here:
    }//GEN-LAST:event_ceduMousePressed

    private void ceduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceduActionPerformed

    private void seleccionGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionGActionPerformed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MousePressed

    private void btn_U_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_U_2MousePressed

        // Abrir sección
        Usuario p1 = new Usuario();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_U_2MousePressed

    private void ap2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ap2MouseClicked

    private void nroRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nroRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nroRMouseClicked

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    public void InsertUser(int idus,
            String name, 
            String app, 
            String apm, 
            String fech,
            String matri,
            String mod,
            String nro,
            String carre,
             
            String tel) 
            
            throws SQLException{
        Statement stm = re.createStatement();
        
        //convierte edad
        DateTimeFormatter date=DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaNacimiento=LocalDate.parse(fech, date);
        LocalDate fechaActual=LocalDate.now();
        
        
        Period periodo=Period.between(fechaNacimiento, fechaActual);
        
        
        
        int edad=periodo.getYears();
        //----------------------------
        
         
                ResultSet counter = stm.executeQuery("SELECT * FROM `usuario`");

                int count = 0;
                while(counter.next())
                {count++;}
                
                int i = 0,idn=0;
                ResultSet re = stm.executeQuery("SELECT * FROM `usuario`");
                while(re.next())
                {
                   idn=re.getInt("idUsuario");
                }
        idn++;
        
        
        stm.executeUpdate("INSERT INTO `usuario` (`idUsuario`,`nombre`, `apP`, `apM`, `feN`,`matricula`,`sem_ano`,`nro_est`,`carrera`,`tel`) VALUES ('"+idn+"','"+name+"', '"+app+"', '"+apm+"', '"+fech+"', '"+matri+"','"+mod+"','"+nro+"','"+carre+"','"+tel+"')");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        Usuario p1 = new Usuario();
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);

                        content.removeAll();
                        content.add(p1, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
    }
    
    public void EditUser(int id, 
            String name, 
            String app, 
            String apm, 
            String fech,
            String matri,
            String mod,
            String nro,
            String carre,
            
            String tel) 
            throws SQLException{
        Statement stm = re.createStatement();
        
         DateTimeFormatter date=DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaNacimiento=LocalDate.parse(fech, date);
        LocalDate fechaActual=LocalDate.now();
        
        
        Period periodo=Period.between(fechaNacimiento, fechaActual);
        
        
        
        int edad=periodo.getYears();
        
        
        
        
        stm.executeUpdate("UPDATE `usuario` SET `nombre` = '"+name+"', `apP` = '"+app+"', `apM` = '"+apm+"',`feN`= '"+fech+"',`matricula`= '"+matri+"',`sem_ano`= '"+mod+"',`nro_est`= '"+nro+"',`carrera`= '"+carre+"',`tel`= '"+tel+"' WHERE `idUsuario` = "+ id +";");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        Usuario p1 = new Usuario();
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);

                        content.removeAll();
                        content.add(p1, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField ap1;
    private javax.swing.JTextField ap2;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btn_U_1;
    private javax.swing.JLabel btn_U_2;
    private javax.swing.JPanel button;
    private javax.swing.JPanel button1;
    private javax.swing.JComboBox<String> carr;
    private javax.swing.JTextField cedu;
    private rojeru_san.rsdate.RSDateChooser fech;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nroR;
    private javax.swing.JComboBox<String> seleccionG;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
