/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import JavaSql.JavaMySql;
import Ux.DtableR;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import static Ventanas.Principal_Sistema.content;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP 245 G4
 */
public class Prestamo extends javax.swing.JPanel {

    JavaMySql conn;
    Connection reg;
    
        
          
    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        
        initComponents();
        conn = new JavaMySql();
        reg = conn.conexion();
        
        MostrarDatosP();
    }
    public void MostrarDatosP()
    {
        try{
            Statement stm = reg.createStatement();
            ResultSet re=stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor'");
            int c=0;
            while(re.next())
            {
                c++;
            }
            Object list[][] = new Object[c][6];
           
            ListPres.setDefaultRenderer(Object.class, new DtableR());
            JLabel R=new JLabel(new ImageIcon(getClass().getResource("/images/recibo3.png")));
            ResultSet res=stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor'");
            int i=c;
            while(res.next())
            {
                
                i--;
                list[i][0]=res.getString("idPrestamo");
                list[i][1]=res.getString("CodUsuario");
                list[i][2]=res.getString("CodLibro");
                list[i][3]=res.getString("fechaPr");
                list[i][4]=res.getString("fechaDe");
                list[i][5]=R;
                
                
            }
            
            
            
            
            
            ListPres.setModel(new javax.swing.table.DefaultTableModel(list,new String [] {"COD DE PRÉSTAMO","CÉDULA DE IDENTIDAD", "COD LIBRO", "F. DE PRÉSTAMO","F. DE DEVOLUCIÓN","RECIBO"}));
            ListPres.getColumnModel().getColumn(5).setPreferredWidth(8);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        BuscarReg = new javax.swing.JTextField();
        search = new javax.swing.JPanel();
        BuscarP = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nuevo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPres = new javax.swing.JTable();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        BuscarFech = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("PRÉSTAMOS");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        BuscarReg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BuscarReg.setForeground(new java.awt.Color(102, 102, 102));
        BuscarReg.setText("Ingrese Carnet");
        BuscarReg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BuscarReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarRegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BuscarRegMouseReleased(evt);
            }
        });
        BuscarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRegActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 170, 30));

        search.setBackground(new java.awt.Color(51, 73, 84));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BuscarP.setForeground(new java.awt.Color(255, 255, 255));
        BuscarP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuscarP.setText("BUSCAR PRÉSTAMO");
        BuscarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarPMousePressed(evt);
            }
        });
        search.add(BuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 30));

        delete.setBackground(new java.awt.Color(51, 73, 84));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BORRAR PRÉSTAMO");
        delete.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 180, -1));

        edit.setBackground(new java.awt.Color(51, 73, 84));
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMousePressed(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDITAR PRÉSTAMO");
        edit.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 180, -1));

        nuevo.setBackground(new java.awt.Color(51, 73, 84));
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevoMousePressed(evt);
            }
        });
        nuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NUEVO PRÉSTAMO");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        nuevo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        jPanel1.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 190, -1));

        ListPres.setBackground(new java.awt.Color(255, 255, 0));
        ListPres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListPres.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 13)); // NOI18N
        ListPres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD DE PRÉSTAMO", "CÉDULA DE IDENTIDAD", "COD LIBRO", "F. DE PRÉSTAMO", "F. DE DEVOLUCIÓN", "RBO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListPres.setRowHeight(24);
        ListPres.getTableHeader().setReorderingAllowed(false);
        ListPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListPresMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListPresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(ListPres);
        if (ListPres.getColumnModel().getColumnCount() > 0) {
            ListPres.getColumnModel().getColumn(5).setPreferredWidth(8);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 720, 280));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Por Cédula de Identidad");
        jPanel1.add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 160, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Por Fecha De Préstamo");
        jPanel1.add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 160, -1));

        BuscarFech.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BuscarFech.setForeground(new java.awt.Color(102, 102, 102));
        BuscarFech.setText("Ingrese Fecha");
        BuscarFech.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BuscarFech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarFechMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BuscarFechMouseReleased(evt);
            }
        });
        jPanel1.add(BuscarFech, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRegMousePressed
        if(BuscarReg.getText().equals("Ingrese Carnet"))
        BuscarReg.setText("");
    }//GEN-LAST:event_BuscarRegMousePressed

    private void BuscarRegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRegMouseReleased
        //nothing
    }//GEN-LAST:event_BuscarRegMouseReleased

    private void BuscarPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarPMousePressed
        String f=BuscarFech.getText();
        String r=BuscarReg.getText();
                
 if((!f.equals("Ingrese Fecha") && !f.equals("")) || (!r.equals("Ingrese Carnet")&&!r.equals(""))) 
    {  
                if((!f.equals("Ingrese Fecha") && !f.equals("")) && (!r.equals("Ingrese Carnet")&&!r.equals(""))) 
                {
        try{
            
            
            Statement stm = reg.createStatement();
            ResultSet re=stm.executeQuery("SELECT * FROM prestamo WHERE fechaPr LIKE '"+f+"' AND CodUsuario LIKE '"+r+"'");
            int c=0;
            while(re.next())
            {
                c++;
            }
           String list[][] = new String[c][5];
            ResultSet res=stm.executeQuery("SELECT * FROM prestamo WHERE fechaPr LIKE '"+f+"' AND CodUsuario LIKE '"+r+"'");
            int i=c;
            while(res.next())
            {
                if(res.getString("estado").equals("Deudor"))
                {
                i--;
                list[i][0]=res.getString("idPrestamo");
                list[i][1]=res.getString("CodUsuario");
                list[i][2]=res.getString("CodLibro");
                list[i][3]=res.getString("fechaPr");
                list[i][4]=res.getString("fechaDe");
                }
                
            }
            ListPres.setModel(new javax.swing.table.DefaultTableModel(
                    list,
                    new String [] {
                        "COD DE PRÉSTAMO","CÉDULA DE IDENTIDAD", "COD LIBRO", "F. DE PRÉSTAMO","F. DE DEVOLUCIÓN"
                    }));
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
                else
        {
            if(!f.equals("Ingrese Fecha")&&!f.equals(""))
            {
                try{
            
            
            Statement stm = reg.createStatement();
            ResultSet re=stm.executeQuery("SELECT * FROM prestamo WHERE fechaPr LIKE '"+f+"'");
            int c=0;
            while(re.next())
            {
                c++;
            }
           String list[][] = new String[c][5];
            ResultSet res=stm.executeQuery("SELECT * FROM prestamo WHERE fechaPr LIKE '"+f+"'");
            int i=c;
            while(res.next())
            {
                if(res.getString("estado").equals("Deudor"))
                {
                i--;
                list[i][0]=res.getString("idPrestamo");
                list[i][1]=res.getString("CodUsuario");
                list[i][2]=res.getString("CodLibro");
                list[i][3]=res.getString("fechaPr");
                list[i][4]=res.getString("fechaDe");
                }
                
            }
            ListPres.setModel(new javax.swing.table.DefaultTableModel(
                    list,
                    new String [] {
                        "COD DE PRÉSTAMO","CÉDULA DE IDENTIDAD", "COD LIBRO", "F. DE PRÉSTAMO","F. DE DEVOLUCIÓN"
                    }));
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
            else
            {
                if(!r.equals("Ingrese Carnet")&&!r.equals(""))
                {
                    try{
            
            
            Statement stm = reg.createStatement();
            ResultSet re=stm.executeQuery("SELECT * FROM prestamo WHERE CodUsuario LIKE '"+r+"'");
            int c=0;
            while(re.next())
            {
                c++;
            }
           String list[][] = new String[c][5];
            ResultSet res=stm.executeQuery("SELECT * FROM prestamo WHERE CodUsuario LIKE '"+r+"'");
            int i=c;
            while(res.next())
            {
                if(res.getString("estado").equals("Deudor"))
                {
                i--;
                list[i][0]=res.getString("idPrestamo");
                list[i][1]=res.getString("CodUsuario");
                list[i][2]=res.getString("CodLibro");
                list[i][3]=res.getString("fechaPr");
                list[i][4]=res.getString("fechaDe");
                }
                
            }
            ListPres.setModel(new javax.swing.table.DefaultTableModel(
                    list,
                    new String [] {
                        "COD DE PRÉSTAMO","CÉDULA DE IDENTIDAD", "COD LIBRO", "F. DE PRÉSTAMO","F. DE DEVOLUCIÓN"
                    }));
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
            }
      }
    }
  else
    {
        JOptionPane.showMessageDialog(null,"DEBE INGRESAR AL MENOS UN DATO");
    }
    }//GEN-LAST:event_BuscarPMousePressed

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseExited

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        try {
            String inf = BuscarReg.getText();
            Statement stm = reg.createStatement();
            ResultSet counter = stm.executeQuery("SELECT * FROM `usuario` WHERE nombre LIKE '"+inf+"%'");

            int count = 0;
            while(counter.next()){count++;}

            String list[][] = new String[count][6];
            int i = 0;
            ResultSet re = stm.executeQuery("SELECT * FROM `usuario` WHERE nombre LIKE '"+inf+"%'");
            while(re.next()){
                list[i][0] = re.getString("nombre");
                list[i][1] = re.getString("apP");
                list[i][2] = re.getString("apM");
                list[i][3] = re.getString("feN");
                list[i][4] = re.getString("ci");
                list[i][5] = re.getString("tel");

                i++;
            }

            ListPres.setModel(new javax.swing.table.DefaultTableModel(
                list,
                new String [] {
                    "Nombre","Apellido P.", "Apellido M.", "Fecha de Nacimiento", "Carnet","Telefono"
                }));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_searchMousePressed

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
       
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
    
    }//GEN-LAST:event_deleteMouseExited

    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        try {
            int idcell = ListPres.getSelectedRow();
            if(idcell <= -1){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el usuario a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                Statement stm = reg.createStatement();
                ResultSet counter = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor'");

                int count = 0;
                while(counter.next()){count++;}

                String list[][] = new String[count][7];
                int i = count;
                ResultSet re = stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado` = 'Deudor'");
                while(re.next())
                {
                    i--;
                    list[i][0] = re.getString("idPrestamo");
                    list[i][1] = re.getString("CodUsuario");
                    list[i][2] = re.getString("CodLibro");
                    list[i][3] = re.getString("fechaPr");
                    list[i][4] = re.getString("fechaDe");
                    list[i][5] = re.getString("DiasP");
                    
                }
                String codl=list[idcell][0];
                int id =Integer.parseInt(list[idcell][0].substring(2,list[idcell][0].length()));
                if(id <= 0){
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el usuario a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    Statement stm2=null;
                    try {
                        stm2 = reg.createStatement();
                    } catch (SQLException ex) {
                        Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        stm2.executeUpdate("UPDATE `prestamo` SET `estado` = 'No Deudor' WHERE `idPrestamo`='"+codl+"'");
                        javax.swing.JOptionPane.showMessageDialog(this, "¡Prestamo borrado! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                MostrarDatosP();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteMousePressed

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseExited

    private void editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMousePressed
        try {
            int idcell = ListPres.getSelectedRow();
            
            if(idcell <= -1)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el prestamo a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
               

                Statement stm = reg.createStatement();
                ResultSet counter = stm.executeQuery("SELECT * FROM `prestamo`");

                int count = 0;
                while(counter.next())
                {count++;}

                String list[][] = new String[count][6];
                int i = count;
                ResultSet re = stm.executeQuery("SELECT * FROM `prestamo`");
                while(re.next())
                {
                    i--;
                    list[i][0] = re.getString("idPrestamo");
                    list[i][1] = re.getString("CodUsuario");
                    list[i][2] = re.getString("CodLibro");
                    list[i][3] = re.getString("fechaPr");
                    list[i][4] = re.getString("fechaDe");
                    list[i][5] = re.getString("DiasP");
                    
                    
                }
                 int ext=list[idcell][0].length();
     
                int id=Integer.parseInt(list[idcell][0].substring(2, ext));
                if(id <= 0)
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el usuario a borrar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                else{

                     

                    String usid = list[idcell][0];
                    String idu = list[idcell][1];
                    String idl = list[idcell][2];
                    String fp = list[idcell][3];
                    String fd = list[idcell][4];
                    String dd = list[idcell][5];
                    

                    nuevoPrestamo p1 = new nuevoPrestamo(usid, idu, idl, fp,fd, dd);
                    p1.setSize(750, 430);
                    p1.setLocation(0, 0);

                    content.removeAll();
                    content.add(p1, BorderLayout.CENTER);
                    content.revalidate();
                    content.repaint();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // Abrir sección
        nuevoPrestamo p1 = new nuevoPrestamo();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jLabel3MousePressed

    private void nuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoMouseEntered

    private void nuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoMouseExited

    private void nuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMousePressed
        // Abrir sección
        nuevoPrestamo p1 = new nuevoPrestamo();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_nuevoMousePressed

    private void ListPresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListPresMousePressed
        if(BuscarReg.getText().equals("") || BuscarReg.getText() == null || BuscarReg.getText().equals(" "))
        BuscarReg.setText("Ingrese el nombre de usuario a buscar");
    }//GEN-LAST:event_ListPresMousePressed

    private void BuscarFechMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarFechMousePressed
        if(BuscarFech.getText().equals("Ingrese Fecha"))
    {
        BuscarFech.setText("");
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_BuscarFechMousePressed

    private void BuscarFechMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarFechMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarFechMouseReleased

    private void BuscarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarRegActionPerformed

    private void ListPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListPresMouseClicked
    int colum=ListPres.getColumnModel().getColumnIndexAtX(evt.getX());
    int row=ListPres.getSelectedRow();
    
    if(colum==5)
    {
        
        String idp=ListPres.getValueAt(row, 0).toString();
        String idU=ListPres.getValueAt(row, 1).toString();
        String idL=ListPres.getValueAt(row, 2).toString();
        String feP=ListPres.getValueAt(row, 3).toString();
        String feD=ListPres.getValueAt(row, 4).toString();
        
        ArrayList <recibo> lista = new ArrayList<>();
        recibo listP=new recibo(idp,idU,idL,feP,feD);
        lista.add(listP);
        
        JasperReport reporte;
        try {
            reporte = (JasperReport)JRLoader.loadObject(nuevoPrestamo.class.getResource("/Ventanas/Recibo.jasper"));
        JasperPrint imprimir = JasperFillManager.fillReport(reporte,null,new JRBeanCollectionDataSource(lista));
            
            JasperViewer viewer = new JasperViewer(imprimir, false);
            viewer.show();
        } catch (JRException ex) {
            Logger.getLogger(nuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    }//GEN-LAST:event_ListPresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarFech;
    private javax.swing.JLabel BuscarP;
    private javax.swing.JTextField BuscarReg;
    private javax.swing.JTable ListPres;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nuevo;
    private javax.swing.JPanel search;
    // End of variables declaration//GEN-END:variables
}
