/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import JavaSql.JavaMySql;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class Principal extends javax.swing.JPanel {
JavaMySql conn;
    Connection reg;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conn = new JavaMySql();
        reg = conn.conexion();
        
        try{
            Statement stm = reg.createStatement();
            Statement stm2 = reg.createStatement();
            
       
            ResultSet r=stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado`='Deudor'");
            
            while(r.next())
            {
              if(numeroD(r.getString("fechaPr"))>5)
              {stm2.executeUpdate("INSERT INTO `moroso` (`idmoroso`,`matriculaD`, `idlibro`, `idprestamo`, `fechaP`,`fechaD`) VALUES ('"+GeneraCodM()+"','"+r.getString("CodUsuario")+"', '"+r.getString("CodLibro")+"', '"+r.getString("idPrestamo")+"', '"+r.getString("fechaPr")+"', '"+r.getString("fechaDe")+"')");}   
            }
            
            
            
            
            ResultSet res=stm.executeQuery("SELECT * FROM `prestamo` WHERE `estado`='Deudor'");
            
            while(res.next())
            {
              if(numeroD(res.getString("fechaPr"))>5)
              {stm2.executeUpdate("UPDATE `prestamo` SET `estado` = 'moroso' WHERE `idPrestamo`='"+res.getString("idPrestamo")+"'");
              }
            
            }
            mostrarMor();
        }
       
        catch(SQLException ex)
        {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void mostrarMor() throws SQLException
    {
            Statement stm = reg.createStatement();
            Statement stm2 = reg.createStatement();
            int c=0;
            ResultSet r=stm.executeQuery("SELECT `idPrestamo` FROM `prestamo` WHERE `estado` = 'moroso'");
            while(r.next())
            {
                ResultSet m=stm2.executeQuery("SELECT * FROM `moroso` WHERE `idprestamo` = '"+r.getString("idPrestamo")+"'");
                while(m.next())
                {   
                c++;
                }
            }
            
            
            
            
            
            String list[][] = new String[c][5];
            ResultSet res=stm.executeQuery("SELECT `idPrestamo` FROM `prestamo` WHERE `estado` = 'moroso'");
            int i=c;
            while(res.next())
            {
                ResultSet n=stm2.executeQuery("SELECT * FROM `moroso` WHERE `idprestamo` = '"+res.getString("idPrestamo")+"'");
                while(n.next())
                {   
                i--;
                list[i][0]=n.getString("fechaP");
                list[i][1]=n.getString("fechaD");
                list[i][2]=n.getString("matriculaD");
                list[i][3]=CarreraU(n.getString("matriculaD"));
                list[i][4]=n.getString("idlibro");
                }
            }
            
            
            listD.setModel(new javax.swing.table.DefaultTableModel(
                    list,
                    new String [] {
                        "FECHA DE PRE","FECHA DE DEV","CÉDULA DE IDENTIDAD", "CARRERA", "ID LIBRO"
                    }));
    }
   
    private String CarreraU(String c) throws SQLException
    {
        String carrera="";
        Statement stm = reg.createStatement();
        ResultSet r=stm.executeQuery("SELECT * FROM `usuario` WHERE `matricula` = '"+c+"'");
        while(r.next())
        {
            carrera=r.getString("carrera");
        }
        
        return carrera;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listD = new javax.swing.JTable();
        Title2 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("ADMINISTRADORA");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Sistema de Gestión para Biblioteca Pública. Controle y administre de");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("forma óptima y fácil el flujo de préstamos y devoluciones de Libros. ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Esta herramienta le permitirá llevar un control completo de su Biblioteca,");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("tendrá acceso a herramientas especiales para tareas específicas, como:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("• Sección de Reportes");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("• Préstamos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("• Devoluciones");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("• Registro de Estudiantes y Libros Nuevos");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 320, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("• Edición de Estudiantes y Libros existentes");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("• Eliminar todo tipo de Registros");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 330, -1));

        Title1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        Title1.setText("DEUDORES MOROSOS");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 220, -1));

        listD.setBackground(new java.awt.Color(255, 58, 11));
        listD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 11)); // NOI18N
        listD.setForeground(new java.awt.Color(255, 255, 255));
        listD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA PRE", "FECHA DEV", "CÉDULA DE IDENTIDAD", "CARRERA", "ID LIBRO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listD.setRowHeight(20);
        jScrollPane2.setViewportView(listD);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 480, 180));

        Title2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title2.setText("BIBLIOTECA UNIVERSITARIA UBI");
        add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, -1));

        Title3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Title3.setText("EST MARIA ELENA ROJAS LUCANA");
        add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/BIBLIO.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 260, 140));
    }// </editor-fold>//GEN-END:initComponents

/*inicio de procesos*/
    
    private int GeneraCodM()throws SQLException
    {
        int cod=0;
        boolean sw=false;
        
        Statement stm = reg.createStatement();
        ResultSet res=stm.executeQuery("SELECT `idmoroso` FROM `moroso`");
         while(res.next())
        {
            sw=true;
            cod=res.getInt("idmoroso");
        }
         if(sw)
         {
             cod++;
         }
         else
         {
             cod=1;
         }
      return cod;
    }
    private int numeroD(String a1)
    {
        String a=a1;
        
        Date fecha=new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
        
        String fa=formatoFecha.format(fecha);
        
        int c=0;
        
        fa=NextFecha(fa);
        
        do{ c++;
        
            a=NextFecha(a);
        
        }while(!a.equals(fa));
        
        
        
        return c;
    }

    
    
    
    
    
    
    private String NextFecha(String f)
{
    
    String dia=f.substring(0,2);
    
    
    
    
    int d=Integer.parseInt(dia);
  
    
    
    
    
    String mes=f.substring(3,5);
    
    
    int m=Integer.parseInt(mes);
   /*JOptionPane.showMessageDialog(null," "+mes);*/
   
    String year=f.substring(6,10);
    
    int y=Integer.parseInt(year);
    /*JOptionPane.showMessageDialog(null," "+year);*/
    
    
    String Nenfecha="";
    
    switch(mes)
    {
        case "01":
            if(d<31)
            {
                
                d=d+1;
                 if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
               
            }
            else
            {
                Nenfecha="01/02/"+year;
            }
            break;
        case "02":
            
            if(bisiesto2(y))
            {
                if(d<29)
                {
                    d=d+1;
                    if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
                }
                else
                {
                    Nenfecha="01/03/"+year;
                }
            }
            else
            {
                 if(d<28)
                {
                     d=d+1;
                   if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
                }
                else
                {
                    Nenfecha="01/03/"+year;
                }
            }
             break;
        case "03":
             if(d<31)
            {
                d=d+1;
                
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/04/"+year;
            }
              break;
        case "04":
            if(d<30)
            {
                d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/05/"+year;
            }
             break;
        case "05":
            if(d<31)
            {d=d+1;
                
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/06/"+year;
            }
             break;
        case "06":
            if(d<30)
            {d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/07/"+year;
            }
             break;
        case "07":
            if(d<31)
            {d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/08/"+year;
            }
             break;
        case "08":
            if(d<31)
            {d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/09/"+year;
            }
             break;
        case "09":
            if(d<30)
            {d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/10/"+year;
            }
 break;
        case "10":
            if(d<31)
            {
                d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/11/"+year;
            }
             break;
        case "11":
                if(d<30)
            {d=d+1;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                Nenfecha="01/12/"+year;
            }
                 break;
        case "12":
            if(d<31)
            {
                d++;
                if(d<10)
                 {
                     Nenfecha="0"+d+"/"+mes+"/"+year;
                 }
                 else
                 {
                     Nenfecha=Integer.toString(d)+"/"+mes+"/"+year;
                 }
            }
            else
            {
                y++;
                Nenfecha="01/01/"+Integer.toString(y);
            }

             break;
            
            
    }
    /*JOptionPane.showMessageDialog(null,"sgte fecha "+Nenfecha);*/
    return Nenfecha;
}
public boolean bisiesto2(int ano){
    
    if((ano % 4 == 0 && ano % 100 != 0)|| ano % 400 == 0)
    {
        return true;
    }
    else{
        return false;
    }
}
    
  
    
    
    
    
    
/*fin de procesos*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JPanel body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listD;
    // End of variables declaration//GEN-END:variables
}
