/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import JavaSql.JavaMySql;
import static Ventanas.Principal_Sistema.content;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import static java.util.Collections.list;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class Reports extends javax.swing.JPanel {

    JavaMySql conn;
    Connection reg;

    /**
     * Creates new form Principal
     */
    public Reports() {
        initComponents();
        conn = new JavaMySql();
        reg = conn.conexion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        generaR = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        PfechaB = new rojeru_san.rsdate.RSDateChooser();
        PfechaA = new rojeru_san.rsdate.RSDateChooser();
        Ucarrera = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        deudor = new javax.swing.JCheckBox();
        nodeudor = new javax.swing.JCheckBox();
        moroso = new javax.swing.JCheckBox();
        Title1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Title.setText("PRÉSTAMOS POR FECHA");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 170, -1));

        jPanel1.setBackground(new java.awt.Color(51, 73, 84));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("          CANCELAR");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 120, 60));

        jPanel2.setBackground(new java.awt.Color(51, 73, 84));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        generaR.setBackground(new java.awt.Color(255, 255, 255));
        generaR.setForeground(new java.awt.Color(255, 255, 255));
        generaR.setText("   GENERAR REPORTE");
        generaR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generaR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generaRMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generaR, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(generaR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 130, 60));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 30, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 680, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 238, 370, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 10, 270));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setText("DE FECHA");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 70, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 370, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 470, 10));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 10, 270));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 10, 270));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 70, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel22.setText("A FECHA");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 70, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel24.setText("POR CARRERA DE ESTUDIANTES");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 180, -1));

        PfechaB.setBackground(new java.awt.Color(51, 73, 84));
        PfechaB.setColorBackground(new java.awt.Color(51, 73, 84));
        PfechaB.setColorButtonHover(new java.awt.Color(51, 73, 84));
        PfechaB.setColorDiaActual(new java.awt.Color(51, 73, 84));
        PfechaB.setColorForeground(new java.awt.Color(0, 0, 0));
        PfechaB.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        PfechaB.setFormatoFecha("dd/MM/yyyy");
        PfechaB.setFuente(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        PfechaB.setMaximumSize(new java.awt.Dimension(300, 200));
        PfechaB.setPreferredSize(new java.awt.Dimension(100, 20));
        add(PfechaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 160, 30));

        PfechaA.setBackground(new java.awt.Color(51, 73, 84));
        PfechaA.setColorBackground(new java.awt.Color(51, 73, 84));
        PfechaA.setColorButtonHover(new java.awt.Color(51, 73, 84));
        PfechaA.setColorDiaActual(new java.awt.Color(51, 73, 84));
        PfechaA.setColorForeground(new java.awt.Color(0, 0, 0));
        PfechaA.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        PfechaA.setFormatoFecha("dd/MM/yyyy");
        PfechaA.setFuente(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        PfechaA.setMaximumSize(new java.awt.Dimension(300, 200));
        PfechaA.setPreferredSize(new java.awt.Dimension(100, 20));
        add(PfechaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 160, 30));

        Ucarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las Carreras", "Ing de Sistemas y TIC", "ContadurÍa y AuditorÍa de Sistemas", "Ing Comercial y Empresarial", "Medicina Veterinaria", "Ing Civil" }));
        Ucarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcarreraActionPerformed(evt);
            }
        });
        add(Ucarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 310, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel19.setText("ESTADO DE ESTUDIANTES");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, 10));

        deudor.setBackground(new java.awt.Color(51, 73, 84));
        deudor.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 13)); // NOI18N
        deudor.setForeground(new java.awt.Color(255, 255, 255));
        deudor.setText("Deudores");
        add(deudor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 120, -1));

        nodeudor.setBackground(new java.awt.Color(51, 73, 84));
        nodeudor.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 13)); // NOI18N
        nodeudor.setForeground(new java.awt.Color(255, 255, 255));
        nodeudor.setText("No Deudores");
        add(nodeudor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 120, -1));

        moroso.setBackground(new java.awt.Color(51, 73, 84));
        moroso.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 13)); // NOI18N
        moroso.setForeground(new java.awt.Color(255, 255, 255));
        moroso.setText("Deudores Morosos");
        add(moroso, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 160, -1));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("REPORTE DE PRÉSTAMOS");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/reporte.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 250, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void generaRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generaRMousePressed

        /*oteniendo datos de fechas*/
        String A = DevFecha(PfechaA.getDatoFecha());
        System.out.println("A = " + A);
        String B = DevFecha(PfechaB.getDatoFecha());
        System.out.println("B = " + B);

        if ((!A.equals("Seleccinar fecha") && !A.equals("")) && (!B.equals("Seleccinar fecha") && !B.equals(""))) {
            /*oteniendo datos de usuario*/

            String Carrera = (String) Ucarrera.getSelectedItem();

            /*oteniendo datos de Libro*/
            if (deudor.isSelected() && nodeudor.isSelected() && moroso.isSelected()) {
                String e1 = "Deudor";
                String e2 = "No Deudor";
                String e3 = "moroso";
                Reporte_Prestamos p1;
                try {
                    p1 = new Reporte_Prestamos(A, B, Carrera, e1, e2, e3);
                    p1.setSize(750, 430);
                    p1.setLocation(0, 0);
                    content.removeAll();
                    content.add(p1, BorderLayout.CENTER);
                    content.revalidate();
                    content.repaint();
                } catch (SQLException ex) {
                    Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                if (deudor.isSelected() && nodeudor.isSelected()) {
                    String e1 = "Deudor";
                    String e2 = "No Deudor";
                    Reporte_Prestamos p1;
                    try {
                        p1 = new Reporte_Prestamos(A, B, Carrera, e1, e2);
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);
                        content.removeAll();
                        content.add(p1, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
                    } catch (SQLException ex) {
                        Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    if (deudor.isSelected() && moroso.isSelected()) {
                        String e1 = "Deudor";
                        String e2 = "moroso";
                        Reporte_Prestamos p1;
                        try {
                            p1 = new Reporte_Prestamos(A, B, Carrera, e1, e2);
                            p1.setSize(750, 430);
                            p1.setLocation(0, 0);
                            content.removeAll();
                            content.add(p1, BorderLayout.CENTER);
                            content.revalidate();
                            content.repaint();
                        } catch (SQLException ex) {
                            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        if (nodeudor.isSelected() && moroso.isSelected()) {
                            String e1 = "No Deudor";
                            String e2 = "moroso";
                            Reporte_Prestamos p1;
                            try {
                                p1 = new Reporte_Prestamos(A, B, Carrera, e1, e2);
                                p1.setSize(750, 430);
                                p1.setLocation(0, 0);
                                content.removeAll();
                                content.add(p1, BorderLayout.CENTER);
                                content.revalidate();
                                content.repaint();
                            } catch (SQLException ex) {
                                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {
                            if (deudor.isSelected()) {
                                String estado = "Deudor";
                                Reporte_Prestamos p1;
                                try {
                                    p1 = new Reporte_Prestamos(A, B, Carrera, estado);
                                    p1.setSize(750, 430);
                                    p1.setLocation(0, 0);
                                    content.removeAll();
                                    content.add(p1, BorderLayout.CENTER);
                                    content.revalidate();
                                    content.repaint();
                                } catch (SQLException ex) {
                                    Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                                if (nodeudor.isSelected()) {
                                    String estado = "No Deudor";
                                    Reporte_Prestamos p1;
                                    try {
                                        p1 = new Reporte_Prestamos(A, B, Carrera, estado);
                                        p1.setSize(750, 430);
                                        p1.setLocation(0, 0);
                                        content.removeAll();
                                        content.add(p1, BorderLayout.CENTER);
                                        content.revalidate();
                                        content.repaint();
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                                    }

                                } else {
                                    if (moroso.isSelected()) {
                                        String estado = "moroso";
                                        Reporte_Prestamos p1;
                                        try {
                                            p1 = new Reporte_Prestamos(A, B, Carrera, estado);
                                            p1.setSize(750, 430);
                                            p1.setLocation(0, 0);
                                            content.removeAll();
                                            content.add(p1, BorderLayout.CENTER);
                                            content.revalidate();
                                            content.repaint();
                                        } catch (SQLException ex) {
                                            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                                        }

                                    } else {
                                        String e1 = "Deudor";
                                        String e2 = "No Deudor";
                                        String e3 = "moroso";
                                        Reporte_Prestamos p1;
                                        try {
                                            p1 = new Reporte_Prestamos(A, B, Carrera, e1, e2, e3);
                                            p1.setSize(750, 430);
                                            p1.setLocation(0, 0);
                                            content.removeAll();
                                            content.add(p1, BorderLayout.CENTER);
                                            content.revalidate();
                                            content.repaint();
                                        } catch (SQLException ex) {
                                            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }

                            }

                        }

                    }

                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR LAS FECHAS ");
        }

        /*String A=DevFecha(PfechaA.getDatoFecha());
          String B=DevFecha(PfechaB.getDatoFecha());
        
        Statement stm;
        try {
            stm = reg.createStatement();
        
            
        
        if(A!=null && B!=null)
        {
           
            
            
            
            
            
             String list[][] = new String[50][10];
            do{
                ResultSet re=stm.executeQuery("SELECT * FROM `prestamo` WHERE `fechaPr` = "+A+"");
                int i = 0;
                while(re.next())
                {
                  list[i][0]=re.getString("idPrestamo");
                  list[i][1]=re.getString("idPrestamo");
                  list[i][2]=deNombre(re.getString("matricula"));
                  list[i][3]=dePaterno(re.getString("matricula"));
                  list[i][4]=deMaterno(re.getString("matricula"));
                  list[i][5]=re.getString("matricula");
                  list[i][6]=deCarrera(re.getString("matricula"));
                  list[i][7]=deTituloL(re.getString("CodLibro"));
                  list[i][8]=deCategoriaL(re.getString("CodLibro"));
                  list[i][9]="no deudor";
                  i++;
                          
                }
                A=NextFecha(A);
            }while(A!=B);
        }
        
        
        
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Reporte_Prestamos p1=new Reporte_Prestamos(list[50][10]);
        p1.setSize(750, 430);
        p1.setLocation(0,0);
                

         */
// TODO add your handling code here:
    }//GEN-LAST:event_generaRMousePressed

//    private String DevFecha(Date f) {
//        char af, bf, c, d, e, g;
//        SimpleDateFormat fc = new SimpleDateFormat();
//        if (f != null) {
//            String fec = fc.format(f);
//
//            af = fec.charAt(0);
//            String dia1 = Character.toString(af);
//            bf = fec.charAt(1);
//            String dia2 = Character.toString(bf);
//
//            c = fec.charAt(3);
//            String m1 = Character.toString(c);
//            d = fec.charAt(4);
//            String m2 = Character.toString(d);
//
//            e = fec.charAt(6);
//            String y1 = Character.toString(e);
//            g = fec.charAt(7);
//            String y2 = Character.toString(g);
//
//            String nfecha = dia1 + dia2 + "/" + m1 + m2 + "/20" + y1 + y2;
//
//            return nfecha;
//        } else {
//
//            return "";
//        }
//
//    }
    private String DevFecha(Date f) {
        if (f != null) {
            SimpleDateFormat fc = new SimpleDateFormat("dd/MM/yyyy");
            return fc.format(f);
        } else {
            return "";
        }
    }
    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        //METODO PARA IR ATRAS
        // Abrir sección
        ReportesG p1 = new ReportesG();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jLabel7MousePressed

    private void UcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UcarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UcarreraActionPerformed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsdate.RSDateChooser PfechaA;
    private rojeru_san.rsdate.RSDateChooser PfechaB;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JComboBox<String> Ucarrera;
    private javax.swing.JPanel body;
    private javax.swing.JCheckBox deudor;
    private javax.swing.JLabel generaR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JCheckBox moroso;
    private javax.swing.JCheckBox nodeudor;
    // End of variables declaration//GEN-END:variables
}
